import AdmZip from 'adm-zip';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import backendPackageJson from '../../package.json';
import type { Step } from '../types/step';
import { exportToSpec } from './exporter';

export interface ProjectExportOptions {
  testName: string;
  testUrl: string;
  steps: Step[];
  variables?: Record<string, string>;
  useEnvVars?: boolean;
}

export interface ProjectExportResult {
  filename: string;
  buffer: Buffer;
}

function sanitizeFilename(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function collectTemplateNames(text: string | null | undefined, names: Set<string>) {
  if (!text) return;
  const re = /\{\{(\w+)\}\}/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(text)) !== null) {
    names.add(match[1]);
  }
}

function collectVariableNames(testUrl: string, steps: Step[]) {
  const names = new Set<string>();
  collectTemplateNames(testUrl, names);
  for (const step of steps) {
    collectTemplateNames(step.selector, names);
    collectTemplateNames(step.value, names);
    collectTemplateNames(step.expected, names);
  }
  return Array.from(names).sort((a, b) => a.localeCompare(b));
}

function countAssertions(steps: Step[]) {
  return steps.filter((step) => step.action.startsWith('assert')).length;
}

function normalizeSteps(testUrl: string, steps: Step[]) {
  const firstStep = steps[0];
  if (firstStep?.action === 'goto') {
    if (firstStep.value?.trim()) {
      return steps;
    }

    if (testUrl.trim()) {
      const gotoStep: Step = { ...firstStep, value: testUrl };
      return [gotoStep, ...steps.slice(1)];
    }

    return steps;
  }

  if (testUrl.trim()) {
    const gotoStep: Step = { action: 'goto', value: testUrl };
    return [gotoStep, ...steps];
  }

  return steps;
}

function buildPackageJson() {
  const playwrightVersion = backendPackageJson.dependencies?.['@playwright/test'] ?? '^1.59.1';

  return JSON.stringify(
    {
      name: 'wrighttest-export',
      private: true,
      scripts: {
        test: 'playwright test'
      },
      devDependencies: {
        '@playwright/test': playwrightVersion
      }
    },
    null,
    2
  );
}

function buildPlaywrightConfig() {
  return `import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  use: {
    headless: true
  }
});
`;
}

function buildGitignore() {
  return `node_modules
playwright-report
test-results
.env
`;
}

function buildEnvExample(variableNames: string[]) {
  return `${variableNames.map((name) => `${name}=`).join('\n')}${variableNames.length > 0 ? '\n' : ''}`;
}

function buildReadme(testName: string, assertionsCount: number, hasEnvVars: boolean) {
  const lines = [
    '# Generated by WrightTest',
    '',
    `This project was exported from the check "${testName}".`,
    '',
    '## Install dependencies',
    '',
    'npm install',
    '',
    '## Install browsers',
    '',
    'npx playwright install',
    '',
    '## Run tests',
    '',
    'npx playwright test',
    ''
  ];

  if (hasEnvVars) {
    lines.push(
      '## Environment variables',
      '',
      'Copy `.env.example` to `.env` and set the required values before running the test.',
      ''
    );
  }

  if (assertionsCount === 0) {
    lines.push('Warning: this exported test does not contain assertions yet.', '');
  }

  return lines.join('\n');
}

async function zipDirectoryToBuffer(directoryPath: string) {
  const zip = new AdmZip();
  zip.addLocalFolder(directoryPath);
  return zip.toBuffer();
}

export async function buildPlaywrightProjectZip(options: ProjectExportOptions): Promise<ProjectExportResult> {
  const { testName, testUrl, steps, variables = {}, useEnvVars = false } = options;
  const tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'wrighttest-export-'));
  const projectRoot = path.join(tempRoot, 'wrighttest-export');
  const testsDir = path.join(projectRoot, 'tests');
  const specBaseName = sanitizeFilename(testName) || 'check';
  const specFileName = `${specBaseName}.spec.ts`;
  const variableNames = collectVariableNames(testUrl, steps);
  const exportSteps = normalizeSteps(testUrl, steps);
  const assertionsCount = countAssertions(exportSteps);
  const hasEnvVars = useEnvVars && variableNames.length > 0;

  await fs.mkdir(testsDir, { recursive: true });
  await fs.writeFile(path.join(projectRoot, 'package.json'), `${buildPackageJson()}\n`, 'utf8');
  await fs.writeFile(path.join(projectRoot, 'playwright.config.ts'), buildPlaywrightConfig(), 'utf8');
  await fs.writeFile(path.join(projectRoot, '.gitignore'), buildGitignore(), 'utf8');
  await fs.writeFile(path.join(projectRoot, 'README.md'), `${buildReadme(testName, assertionsCount, hasEnvVars)}\n`, 'utf8');

  if (hasEnvVars) {
    await fs.writeFile(path.join(projectRoot, '.env.example'), buildEnvExample(variableNames), 'utf8');
  }

  const spec = exportToSpec(exportSteps, {
    testName,
    variables,
    useEnvVars
  });
  await fs.writeFile(path.join(testsDir, specFileName), spec, 'utf8');

  try {
    const buffer = await zipDirectoryToBuffer(projectRoot);
    return {
      filename: `${specBaseName}-playwright-project.zip`,
      buffer
    };
  } finally {
    await fs.rm(tempRoot, { recursive: true, force: true }).catch(() => undefined);
  }
}
